export type Testimonial = {
  name: string
  title: string
  linkedin: string
  service: string
  rating: number
  date: string
  testimonial: string
  avatar: string
}

export const testimonials: Testimonial[] = [

  {
    name: "Rafael Romis",
    title: "I have nightmares about bad websites, and I can show you exactly why yours is broken",
    linkedin: "https://www.linkedin.com/in/rafaelromis",
    service: "Book Marketing & Promotion",
    rating: 5,
    date: "August 21, 2025",
    testimonial: "Syed is a pro when it comes to book marketing and promotion. He really helped me a bunch when launching my first book and when I didn't know what to do. What I appreciate the most is how he tailors strategies to your unique situation instead of rinse-and-repeat tactics.",
    avatar: "/images/testimonials/rafael-romis.jpg",
  },
  {
    name: "Daniel Jackman",
    title: "Certified Chair, Entrepreneur with multi-national company experience | Board member/Independent Director | Finance expert",
    linkedin: "https://www.linkedin.com/in/daniel-jackman-03956b2",
    service: "Marketing Consulting",
    rating: 5,
    date: "July 14, 2025",
    testimonial: "We have worked with Syed for over three years. His work specializes in Amazon ads for our English, German, and Spanish editions across multiple markets. If you publish your books on Amazon, Syed can help you reach a wider audience and drive greater sales.",
    avatar: "/images/testimonials/daniel-jackman.jpg",
  },
  {
    name: "Michael Ehiginwa (PMP, CBAP, ITIL)",
    title: "Author | Business Consultant | Senior Business Analyst | Empowering Individuals to Achieve Their Goals",
    linkedin: "https://www.linkedin.com/in/michael-ehiginwa-pmp-cbap-itil-49b78420",
    service: "Book Marketing",
    rating: 5,
    date: "February 3, 2025",
    testimonial: "I worked with Syed for about five months on my book. He was very professional and brought deep insights into book marketing. His experience is profound and his objectivity refreshing. I will definitely want to work with Syed again.",
    avatar: "/images/testimonials/michael-ehiginwa--pmp--cbap--itil-.jpg",
  },
  {
    name: "Nick Singleton",
    title: "Regional Director at Global Scouting Bureau",
    linkedin: "https://www.linkedin.com/in/nick-singleton-154b1063",
    service: "Publishing Strategy",
    rating: 5,
    date: "December 19, 2024",
    testimonial: "Syed actively engages with his clients to gather the information needed to drive success. I would recommend him to anyone wanting to publish books; his industry knowledge and work ethic are top tier.",
    avatar: "/images/testimonials/nick-singleton.jpg",
  },
  {
    name: "Hisham Sarwar",
    title: "CEO Innovista | Digital Marketing Consultant & Founder of WorkChest.com",
    linkedin: "https://www.linkedin.com/in/hishamsarwar",
    service: "Kindle Publishing & Marketing",
    rating: 5,
    date: "October 8, 2024",
    testimonial: "Syed Saqib Mumtaz is an amazing, skilled resource for Kindle ebook creation and marketing. His added strength is LinkedIn advertising. He is highly knowledgeable and I recommend him for Amazon Kindle Direct Publishing.",
    avatar: "/images/testimonials/hisham-sarwar.jpg",
  },
  {
    name: "Salman Qaisrani",
    title: "Strategic Leader in Public-Private Partnerships (PPP) | MD Salman Qaisrani Foundation",
    linkedin: "https://www.linkedin.com/in/salman-qaisrani-777b391b9",
    service: "Digital Marketing",
    rating: 5,
    date: "October 5, 2024",
    testimonial: "Syed Saqib Mumtaz is an excellent leader in his field and executes his assignments with professionalism and enthusiasm. His analysis and recommended actions are commendable. I worked with him on a workshop marketing project and his efforts were far-reaching and effective.",
    avatar: "/images/testimonials/salman-qaisrani.jpg",
  },
  {
    name: "Uma Vanka",
    title: "Partner @ Management Consulting - TCS | Business Strategy, ERP & Digital Transformation",
    linkedin: "https://www.linkedin.com/in/umavanka",
    service: "Marketing Operations",
    rating: 5,
    date: "April 25, 2024",
    testimonial: "Reliability, ownership and attention to detail are the three qualities you get from Syed. You can hand him your marketing activities and he will manage them end-to-end, celebrating wins and being transparent when something can't be delivered. I've worked with him for years and that ownership keeps me coming back.",
    avatar: "/images/testimonials/uma-vanka.jpg",
  },
  {
    name: "Roua Arfaoui",
    title: "Head of Marketing",
    linkedin: "https://www.linkedin.com/in/roua-arfaoui-0b4464115",
    service: "Amazon SEO & Advertising",
    rating: 5,
    date: "April 1, 2024",
    testimonial: "I had the pleasure of working with Syed on promoting my client's book on Amazon, and his expertise made a significant difference. He understands Amazon's algorithms and SEO strategies, which boosted visibility and sales. His proactive approach, attention to detail and dedication to results were truly impressive.",
    avatar: "/images/testimonials/roua-arfaoui.jpg",
  },
  {
    name: "Yasmin Elahi",
    title: "Author",
    linkedin: "https://www.linkedin.com/in/yasmin-elahi-a7421151",
    service: "Social Media Marketing",
    rating: 5,
    date: "November 7, 2023",
    testimonial: "It was really a pleasure to interact with Syed Saqib Mumtaz. He knows his job well, is polite, patient, and very cooperative. He guided me through promoting my book on Facebook and his advice was beyond excellent. I highly recommend him if you want value for your money.",
    avatar: "/images/testimonials/yasmin-elahi.jpg",
  },
  {
    name: "Kevin Romanteau",
    title: "Event-Driven | Investor | Finance Author",
    linkedin: "https://www.linkedin.com/in/kevinromanteau",
    service: "Marketing Strategy",
    rating: 5,
    date: "August 19, 2023",
    testimonial: "I had the pleasure to consult Syed for launching my book and can confidently say that he is dedicated and well-qualified.",
    avatar: "/images/testimonials/kevin-romanteau.jpg",
  },
  {
    name: "Gavin Coyle CMIOSH I MBS",
    title: "CEO | Safety Recruitment Specialist & Business Expert | Podcast Host | Board Advisor | Amazon Author",
    linkedin: "https://www.linkedin.com/in/gavincoyleceo",
    service: "Digital Marketing",
    rating: 5,
    date: "January 20, 2023",
    testimonial: "Syed is amazing, he is a true expert in his field. He is always available and makes great recommendations to help make your book No. 1 in its category. He also plays a vital role in managing how your book receives traffic on Amazon. Highly recommended.",
    avatar: "/images/testimonials/gavin-coyle-cmiosh-i-mbs.jpg",
  },
  {
    name: "Kashmir Maryam, MFT",
    title: "Therapist | Author | Founding Director of Heal Therapy Clinic",
    linkedin: "https://www.linkedin.com/in/kashmir-maryam-mft-a0b89491",
    service: "Amazon KDP Marketing",
    rating: 5,
    date: "December 16, 2022",
    testimonial: "Syed did a wonderful job of marketing my books on Amazon KDP. He is very knowledgeable in his field and offered great professional advice throughout the process. I highly recommend him.",
    avatar: "/images/testimonials/kashmir-maryam--mft.jpg",
  },
  {
    name: "Nauman Munir Afzal",
    title: "Director Admin",
    linkedin: "https://www.linkedin.com/in/nauman-munir-afzal-956b287",
    service: "Marketing Strategy",
    rating: 5,
    date: "November 21, 2022",
    testimonial: "He's a professional with a very positive attitude who sticks to timelines.",
    avatar: "/images/testimonials/nauman-munir-afzal.jpg",
  },
  {
    name: "Brenda Bence, Ranked Top Ten Coach Globally",
    title: "High-Stakes C-Suite Succession & Leadership Coach/Advisor | Trusted by Boards, CEOs & ELTs | Harvard MBA",
    linkedin: "https://www.linkedin.com/in/brendabence",
    service: "Digital Marketing",
    rating: 5,
    date: "November 20, 2022",
    testimonial: "I have worked with Syed for the past year as he helped me advertise one of our books on Amazon. He was devoted to doing everything he could to help the book achieve strong sales, and that focus has paid off with multiple bestseller status. I am grateful for his attention and suggestions!",
    avatar: "/images/testimonials/brenda-bence--ranked-top-ten-coach-globally.jpg",
  },
  {
    name: "Leah Stockford",
    title: "Music Marketing Consultant / Author",
    linkedin: "https://www.linkedin.com/in/leah-stockford-1459ab71",
    service: "Digital Marketing",
    rating: 5,
    date: "November 13, 2022",
    testimonial: "I've worked with Saqib for over a year on Amazon Advertising for my books. He's helped me become a frequent No. 1 bestseller and continues to grow my business. Highly recommended.",
    avatar: "/images/testimonials/leah-stockford.jpg",
  },
  {
    name: "Adnan Zaka",
    title: "Educator & Digital Marketing Strategist",
    linkedin: "https://www.linkedin.com/in/adnan-zaka",
    service: "Digital Marketing",
    rating: 5,
    date: "November 11, 2022",
    testimonial: "Syed Saqib is an exceptional digital marketer. He audited our entire bookshelf, recommended key changes, and re-planned our launches with unique strategies. Working with him is a pleasure and has been very fruitful. We're now collaborating on multiple new projects.",
    avatar: "/images/testimonials/adnan-zaka.jpg",
  },
  {
    name: "Albert Griesmayr",
    title: "CEO at Scribando | Novelify | Book Marketing Expert",
    linkedin: "https://www.linkedin.com/in/albertgriesmayr",
    service: "Amazon Advertising & SEO",
    rating: 5,
    date: "November 8, 2022",
    testimonial: "I got to know and value Syed as a trusted provider of Amazon Ads and Amazon SEO data over the last few years. I've consulted with him on multiple advertising campaigns and his input was always valuable. He combines book marketing experience with a strong understanding of data and a passion for making books successful.",
    avatar: "/images/testimonials/albert-griesmayr.jpg",
  },
  {
    name: "Ann S.",
    title: "Founder of LifeLift",
    linkedin: "https://www.linkedin.com/in/ann-shivas",
    service: "Digital Marketing",
    rating: 5,
    date: "November 7, 2022",
    testimonial: "Syed is wonderful to work with, a very good communicator who makes suggestions based on his extensive knowledge. He helped me publish my book in a timely fashion. I highly recommend his services.",
    avatar: "/images/testimonials/ann-s-.jpg",
  },
  {
    name: "M. Azam Awan",
    title: "Tax Accountant | Tax Preparer | CAA for ITIN",
    linkedin: "https://www.linkedin.com/in/azamawan23",
    service: "Digital Marketing",
    rating: 5,
    date: "November 7, 2022",
    testimonial: "Syed is an extremely knowledgeable and expert digital marketer. He creates strategies for book success and has excellent knowledge of Amazon KDP, Amazon PPC, and digital publishing. He is very cooperative to work with.",
    avatar: "/images/testimonials/m--azam-awan.jpg",
  },
  {
    name: "David Angeron",
    title: "Founder of John Melvin University, John Melvin Christian College & John Melvin Publishing",
    linkedin: "https://www.linkedin.com/in/david-angeron-jmu",
    service: "Digital Marketing",
    rating: 5,
    date: "November 3, 2022",
    testimonial: "Syed does great work and is extremely knowledgeable about Amazon advertising.",
    avatar: "/images/testimonials/david-angeron.jpg",
  },
  {
    name: "Syed Waqas Hashmi",
    title: "Amazon KDP Book Publishing Pro | 4000+ Books Published | #1 Bestseller Strategies",
    linkedin: "https://www.linkedin.com/in/syed-waqas-hashmi-a0673838",
    service: "Digital Marketing",
    rating: 5,
    date: "November 3, 2022",
    testimonial: "Syed is a specialist in book marketing and Amazon KDP. He has been instrumental in training me as an Amazon KDP consultant for authors. His innovative ideas and strategies have worked tremendously well for our clients.",
    avatar: "/images/testimonials/syed-waqas-hashmi.jpg",
  },
  {
    name: "Muhammad Saad",
    title: "Amazon KDP Consultant | PPC Ads Manager | SEO Optimizer",
    linkedin: "https://www.linkedin.com/in/muhammadsaadd",
    service: "Digital Marketing",
    rating: 5,
    date: "November 3, 2022",
    testimonial: "It was great working with Syed Saqib. He helped me hit my targeted sales while keeping advertising costs in check. He delivered the best possible services, helped my products rank organically, and provided recommendations at every step.",
    avatar: "/images/testimonials/muhammad-saad.jpg",
  },
]
